"""empty message

Revision ID: 014284a36c4d
Revises: 
Create Date: 2026-09-26 03:58:59.186948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014284a36c4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
